# This file was generated by GoReleaser. DO NOT EDIT.
cask "toci" do
  version "0.1.25"

  on_macos do
    on_arm do
      sha256 "06fe8f1a3275849c2df5aedd5478be340da5b51e9a8d911fe6e901ac4fcce1eb"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "39bf5193f60618318530eb37fc4ed810c635bc52a0a45ad594ecd9fdef596a3c"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "381053f3813fd4201769ccdbbf894d0edc45a69651b2d881b03d77e4cc92fdc4"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6bd373671693a156fe7d2a7727ca7b784e06a918c3cf03e2f48c8cd797112e52"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_amd64.tar.gz"
    end
  end

  name "toci"
  desc "Terminal UI for Oracle Cloud Infrastructure"
  homepage "https://github.com/juseok1729/toci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toci"

  # No zap stanza required
end
