# This file was generated by GoReleaser. DO NOT EDIT.
cask "toci" do
  version "0.1.29"

  on_macos do
    on_arm do
      sha256 "02a86fcf80d7f1e641bc71f22e92c13482d5746de4c867d919033ca8d1a5ac15"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "603d1bb683c871ccf1dc651f5af322f3aaf803ade1293136633bbfb0e7ff9e35"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b512186c9489d3a66d952ee7215467daa11c5bef7c8a4ea98d9c80a0b20dc84"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ff76f28f5e945ec2a0e63f09511fbe5be297c52be1dcd31ab0ad700142a2c5e"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_amd64.tar.gz"
    end
  end

  name "toci"
  desc "Terminal UI for Oracle Cloud Infrastructure"
  homepage "https://github.com/juseok1729/toci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toci"

  # No zap stanza required
end
