# This file was generated by GoReleaser. DO NOT EDIT.
cask "toci" do
  version "0.1.27"

  on_macos do
    on_arm do
      sha256 "9d96f06f00ed462687f0634b71eb572d4ecf567892403da105bfa6263ea0009b"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7af104440b75d5c64e063bc0ef9eef85321f1033650285a93a08bc7d4c384fbe"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "99804141e8ccb6a527aab3fe9cea61cf2a83c14c351fee4e8a4ad565b152de66"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5e6db14e22f17ae7ae16b195b27c35d3aa12d619215a026201b4ea30a6f006a"
      url "https://github.com/juseok1729/toci/releases/download/v#{version}/toci_linux_amd64.tar.gz"
    end
  end

  name "toci"
  desc "Terminal UI for Oracle Cloud Infrastructure"
  homepage "https://github.com/juseok1729/toci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toci"

  # No zap stanza required
end
